### ISSUE TITLE
Add guessing `heic` file mime type by data

### ISSUE THREAD

**Issue by elyahk** [chaqmoq/mime#1]
**Is your feature request related to a problem? Please describe.**
1. This repo doesn't guess `HEIC` file mime type with data. When I tried to guess `HEIC` file from data using `MIME.guess(data: data)`, I got the result with `video/mp4` mime type which is absolutely wrong.
2. This repo doesn't guess `CSV` file mime type with data. When I tried to guess `CSV` file from data using `MIME.guess(data: data)`, I got the result with `application/octet-stream` mime type which is absolutely wrong.

**Describe the solution you'd like**
1. Possible solution is that on the `guess(data: Data)` method, need to add one `if else` case by checking `bytesCount > 11 && (bytes[8...11] == [0x68, 0x65, 0x69, 0x63] || bytes[8...11] == [0x68, 0x65, 0x69, 0x78]` and return `.init("image/heic")` 

Whole code should look like that:
```
  } else if bytesCount > 11 && (bytes[8...11] == [0x68, 0x65, 0x69, 0x63] || bytes[8...11] == [0x68, 0x65, 0x69, 0x78]) {
            return .init("image/heic")
        }
```

2. For the `CSV` file I couldn't find possible solution

**Describe alternatives you've considered**

**Additional context**
I tried to `PR` but unfortunately, I couldn't push my changes because of credientals.  So, I thought it is better to create `issue` on that case. Thanks for fixing this issue in advance

**Comment by sukhrobkhakimov** [comment]
@elyahk There is currently no support for guessing `heic` and `csv` files from bytes.

1. Where did you find out the solution for guessing `heic` files and how did you test it?
2. I also haven't found a way how to guess `csv` files from bytes yet.

As a workaround, you can always guess MIME types for files from `url`, `path`, or `extension`. Usually, files have proper extensions based on their content. If not, a user must add a proper extension.

**Comment by elyahk** [comment]
1. @sukhrobkhakimov  I found the solution on this (REPO)[https://github.com/sendyhalim/Swime/blob/master/Sources/MimeType.swift].
 Tested it using the SD attachment component on my device manually with about 3 examples.
2. https://github.com/NurLight19 suggested me to test `CSV` 5-6 examples, and find patterns by byte codes myself.

**Comment by sukhrobkhakimov** [comment]
@elyahk Since you added support for `image/heic` MIME type and there is no way to guess `text/csv` right now, I am closing this issue.
